### ISSUE TITLE
Evaluate the Global Elections Database

### ISSUE THREAD

**Issue by nbanion** [DataKind-DC/ifes-elections#34]
Evaluate how this dataset might help us answer our motivating questions.

http://www.globalelectionsdatabase.com/

Read the documentation, briefly explore the data, and make a case for or against using this data source. If the data seem promising, then describe some possible uses. If not, then explain the shortcomings. If you are unsure, then write down your questions. No matter what, your investigation is valuable!

Record your findings in the discussion on this issue.

This data set comes from a collection identified on #27.

**Comment by wkarney** [comment]
Took a look at this data (picked it since I went to grad school at WashU). The database (see [GlobalElections_Codebook.pdf](https://github.com/DataKind-DC/ifes-elections/files/5992450/GlobalElections_Codebook.pdf)) focuses on election **results** from a wide variety of countries stretching back to 1946. 

Since there is no temporal data it doesn't seem like a great fit for us. 

That said, it could potentially be used to cross reference with other data that we might have. Results are broken down across political parties and down to the local levels, so maybe we can, for example, identify elections with multi-party systems vs. those that are dominated by 1 or 2 parties and use that as a factor in further analyses.

**Comment by nbanion** [comment]
Thanks @wkarney , very useful. I like the idea of identifying secondary data sources for more nuanced insights later.
